name: 'semver action'
description: 'Simple semver action'
inputs:
  tag-branch:  
    description: 'Use tags of this branch to setup the version'
    required: false
    default: 'main'
  version-prefix:  
    description: 'Prefix of version, either v or V or none'
    required: false
    default: ''
outputs:
  next-version:
    description: "the next version"
    value: ${{ steps.next-version-generator.outputs.next-version }}
  next-major:
    description: "major of next version"
    value: ${{ steps.next-version-generator.outputs.next-major }}
  next-minor:
    description: "minor of next version"
    value: ${{ steps.next-version-generator.outputs.next-minor }}
  next-patch:
    description: "patch of next version"
    value: ${{ steps.next-version-generator.outputs.next-patch }}
runs:
  using: "composite"
  steps:
    - name: get next version
      id: next-version-generator
      shell: bash
      run: semver.sh ${{ inputs.tag-branch }} ${{ inputs.version-prefix }}
