name: 'semver action'
description: 'Simple semver action'
inputs:
  tag-branch:  
    description: 'Use tags of this branch to setup the version'
    required: false
    default: 'main'
  version-prefix:  
    description: 'Prefix of version, either v or V or none'
    required: false
    default: ''
outputs:
  next-version:
    description: "the next version"
    value: ${{ steps.next-version.outputs.next-version }}
  next-major:
    description: "major of next version"
    value: ${{ steps.next-version.outputs.next-major }}
  next-minor:
    description: "minor of next version"
    value: ${{ steps.next-version.outputs.next-minor }}
  next-patch:
    description: "patch of next version"
    value: ${{ steps.next-version.outputs.next-patch }}
runs:
  using: "composite"
  steps:
    - name: get current version
      id: current-version
      shell: bash
      run: |
        prefix="${{ inputs.version-prefix }}"

        # Default version
        version="${prefix}0.0.0"

        # Get the latest git tag
        if [[ ! -z $(git tag) ]]; then
          version=$(git describe --tags --abbrev=0 2>/dev/null)
        fi

        echo "current-version=$version" >> $GITHUB_OUTPUT

    - name: get next version
      id: next-version
      shell: bash
      run: |
        echo "to do"
